### ISSUE TITLE
Bonus: Issue with closing ./cub3D_bonus by clicking on the red cross

### ISSUE THREAD

**Issue by linhtng** [linhtng/cub3d#2]
Closing ./cub3D_bonus by clicking on the red cross will print garbage character to the shell:
c3r3p6%./cub3D_bonus maps/good/test_whitespace.cub
MLX should close...
A�����
c3r3p6% 

The issue doesn't exist for the mandatory part:
c3r3p6% ./cub3D maps/good/test_whitespace.cub
MLX should close...
c3r3p6%

**Comment by jboucher154** [comment]
I changed the mlx hook to properly use the close window function.
