### ISSUE TITLE
Bonus: Consider adding protection/Error management for the frame texture

### ISSUE THREAD

**Issue by linhtng** [linhtng/cub3d#4]
In  setup_cubed_bonus.c file, we have in line 24:
 ((t_cubed_bonus *)cubed)->frame_img = \
	get_new_xpm_image(cubed, "textures/cub3d_tex/cubed_frame_noshade.xpm");

If there is no "textures/cub3d_tex/cubed_frame_noshade.xpm" file to be found, the progamme will crush. In mandatory part, all the texture xpm files are checked if they are valid files in the parsing. We should add the same error management/protection for any extra texture that we used in bonus.

**Comment by jboucher154** [comment]
Added zeroing of the structs int the setup_raycast and setup_cubed, added protection for their null values in the mlx_close function.
